development:
  adapter: mysql2
  encoding: utf8
  database: knowmaths_dev
  pool: 5
  username: root
  password: pass
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: knowmaths_test_api
  pool: 5
  username: root
  password: pass
  host: localhost
